"""
Concrete storage for the Purchases domain, backed by Supabase (Postgres).

This is the ONLY file that knows a `purchases` table exists or what its
columns are -- `PurchasesDomain` / `BooksController` never talk to
Supabase directly, only to the `IPurchaseRepository` contract.

Expected table:

    purchases
    ---------
    id            bigint  generated by default as identity  primary key
    purchase_date date    not null
    book_id       bigint  null
    short_title   varchar null
    category_id   bigint  null
    language_id   bigint  null
    source_id     bigint  null
    qty           bigint  null
    cost_price    double precision  null
    recorded_by   varchar null
    created_at    timestamptz  null
"""

from datetime import date
from typing import Any, Dict, List, Optional

from app.contracts.purchase_repository import IPurchaseRepository
from app.injector import DBContract, injector, singleton
from app.models import Purchase

TABLE = "purchases"


@singleton(IPurchaseRepository)
@injector
class SupabasePurchaseRepository(IPurchaseRepository):
    """`db` (a `DBContract`) is auto-injected by `@injector`. Pass a fake
    explicitly (`SupabasePurchaseRepository(db=FakeDB())`) to unit-test
    this class without touching a real database."""

    def __init__(self, db: DBContract):
        self.db = db

    # -- internal helpers -------------------------------------------------
    @property
    def _table(self):
        return self.db.get_client().table(TABLE)

    @staticmethod
    def _normalize(name: str) -> str:
        return (name or "").strip()

    @staticmethod
    def _serialize(fields: Dict[str, Any], *, drop_none_id: bool = False) -> Dict[str, Any]:
        out = {k: v for k, v in fields.items() if not (k == "id" and v is None and drop_none_id)}
        # dates/decimals serialize fine as-is via the Supabase client;
        # normalize date objects to ISO strings just in case.
        if isinstance(out.get("purchase_date"), date):
            out["purchase_date"] = out["purchase_date"].isoformat()
        if isinstance(out.get("created_at"), date):
            out["created_at"] = out["created_at"].isoformat()
        return out

    @staticmethod
    def _to_model(row: dict) -> Purchase:
        return Purchase(
            id=row["id"],
            purchase_date=row["purchase_date"],
            book_id=row.get("book_id"),
            source_id=row.get("source_id"),        
            qty=row.get("qty"),
            cost_price=row.get("cost_price"),
            recorded_by=row.get("recorded_by"), 
            created_at=row.get("created_at"),
        )

    # -- IPurchaseRepository -----------------------------------------------
    def list_all(self) -> List[Purchase]:
        resp = self._table.select("*").order("purchase_date", desc=True).execute()
        return [self._to_model(row) for row in resp.data or []]

    def get(self, purchase_id: int) -> Optional[Purchase]:
        resp = self._table.select("*").eq("id", purchase_id).limit(1).execute()
        rows = resp.data or []
        return self._to_model(rows[0]) if rows else None

    def find_by_name(self, name: str) -> Optional[Purchase]:
        name = self._normalize(name)
        if not name:
            return None
        resp = (
            self._table.select("*")
            .eq("short_title", name)
            .order("purchase_date", desc=True)
            .limit(1)
            .execute()
        )
        rows = resp.data or []
        return self._to_model(rows[0]) if rows else None

    def add(self, purchase: Purchase) -> Purchase:
        payload = self._serialize(purchase.model_dump(exclude={"id"}), drop_none_id=True)
        resp = self._table.insert(payload).select().execute()
        if resp is None or not resp.data:
            raise RuntimeError("Failed to insert purchase — no data returned.")
        return self._to_model(resp.data[0])

    def add_batch(self, purchases: List[Purchase]) -> List[Purchase]:
        if not purchases:
            return []
        payload = [
            self._serialize(p.model_dump(exclude={"id"}), drop_none_id=True)
            for p in purchases
        ]
        resp = self._table.insert(payload).select().execute()
        if resp is None or not resp.data:
            raise RuntimeError("Failed to insert purchase batch — no data returned.")
        return [self._to_model(row) for row in resp.data]

    def update(self, purchase_id: int, **fields) -> Optional[Purchase]:
        if not fields:
            return self.get(purchase_id)
        patch = self._serialize(fields)
        resp = self._table.update(patch).eq("id", purchase_id).execute()
        rows = resp.data or []
        return self._to_model(rows[0]) if rows else self.get(purchase_id)

    def delete(self, purchase_id: int) -> bool:
        resp = self._table.delete().eq("id", purchase_id).execute()
        return bool(resp.data)

    def name_available(self, name: str) -> bool:
        return self.find_by_name(name) is None

    def list_filtered(
        self,
        *,
        date_from: Optional[date] = None,
        date_to: Optional[date] = None,
        recorded_by: Optional[str] = None,
        book_id: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> List[Purchase]:
        q = self._table.select("*")
        if date_from:
            q = q.gte("purchase_date", date_from.isoformat())
        if date_to:
            q = q.lte("purchase_date", date_to.isoformat())
        if recorded_by:
            q = q.eq("recorded_by", recorded_by)
        if book_id:
            q = q.eq("book_id", book_id)
        q = q.order("purchase_date", desc=True)
        if limit:
            q = q.limit(limit)
        resp = q.execute()
        return [self._to_model(row) for row in resp.data or []]