"""
Concrete storage for the Locations domain, backed by Supabase (Postgres).

This is the ONLY file that knows a `locations` table exists or what its
columns are -- `LocationsDomain` / `LocationsController` never talk to
Supabase directly, only to the `ILocationRepository` contract.

Expected table:

    locations
    ---------
    id      bigint  generated by default as identity  primary key
    name    text    not null
"""

from typing import Any, Dict, List, Optional

from app.contracts.location_repository import ILocationRepository
from app.injector import DBContract, injector, singleton
from app.models import Location

TABLE = "locations"


@singleton(ILocationRepository)
@injector
class SupabaseLocationRepository(ILocationRepository):
    """`db` (a `DBContract`) is auto-injected by `@injector`. Pass a fake
    explicitly (`SupabaseLocationRepository(db=FakeDB())`) to unit-test
    this class without touching a real database."""

    def __init__(self, db: DBContract):
        self.db = db

    # -- internal helpers -------------------------------------------------
    @property
    def _table(self):
        return self.db.get_client().table(TABLE)

    @staticmethod
    def _normalize(name: str) -> str:
        return (name or "").strip()

    @staticmethod
    def _serialize(fields: Dict[str, Any], *, drop_none_id: bool = False) -> Dict[str, Any]:
        out = dict(fields)
        if drop_none_id and out.get("id") is None:
            out.pop("id", None)
        return out

    @staticmethod
    def _to_model(row: dict) -> Location:
        return Location(
            id=row["id"],
            name=row["name"],
        )

    # -- ILocationRepository ------------------------------------------------
    def list_all(self) -> List[Location]:
        resp = self._table.select("*").order("name").execute()
        return [Location(**row) for row in resp.data or []]

    def get(self, location_id: int) -> Optional[Location]:
        resp = self._table.select("*").eq("id", location_id).limit(1).execute()
        rows = resp.data or []
        return Location(**rows[0]) if rows else None

    def find_by_name(self, name: str) -> Optional[Location]:
        name = self._normalize(name)
        if not name:
            return None
        resp = self._table.select("*").eq("name", name).limit(1).execute()
        rows = resp.data or []
        return Location(**rows[0]) if rows else None

    def add(self, location: Location) -> Location:
        payload = self._serialize({"name": self._normalize(location.name)})
        resp = (
            self._table
            .insert(payload)
            .select()
            .execute()
        )
        if resp is None or not resp.data:
            raise RuntimeError(f"Failed to insert location '{location.name}' — no data returned.")
        return self._to_model(resp.data[0])

    def update(self, location_id: int, **fields) -> Optional[Location]:
        if not fields:
            return self.get(location_id)
        patch = self._serialize(fields)
        resp = self._table.update(patch).eq("id", location_id).execute()
        rows = resp.data or []
        return Location(**rows[0]) if rows else self.get(location_id)

    def delete(self, location_id: int) -> bool:
        resp = self._table.delete().eq("id", location_id).execute()
        return bool(resp.data)

    def name_available(self, name: str) -> bool:
        return self.find_by_name(name) is None