"""
Concrete storage for the Catalog (Books) domain, backed by Supabase
(Postgres).

This is the ONLY file that knows a `catalog` table exists or what its
columns are -- `BooksDomain` / `BooksController` never talk to
Supabase directly, only to the `IBookRepository` contract.

Expected table:

    catalog
    -------
    id             bigint  generated by default as identity  primary key
    title          varchar not null
    short_title    varchar null
    category_id    bigint  null
    threshold      bigint  not null
    opening_stock  bigint  null
    created_at     timestamptz null
    updated_at     timestamptz null
"""

from typing import Any, Dict, List, Optional

from app.contracts.book_repository import IBookRepository
from app.injector import DBContract, injector, singleton
from app.models import Book

TABLE = "catalog"


@singleton(IBookRepository)
@injector
class SupabaseBookRepository(IBookRepository):
    """`db` (a `DBContract`) is auto-injected by `@injector`. Pass a fake
    explicitly (`SupabaseBookRepository(db=FakeDB())`) to unit-test this
    class without touching a real database."""

    def __init__(self, db: DBContract):
        self.db = db

    # -- internal helpers -------------------------------------------------
    @property
    def _table(self):
        return self.db.get_client().table(TABLE)

    @staticmethod
    def _normalize(title: str) -> str:
        return (title or "").strip()

    @staticmethod
    def _serialize(fields: Dict[str, Any], *, drop_none_id: bool = False) -> Dict[str, Any]:
        out = dict(fields)
        if drop_none_id and out.get("id") is None:
            out.pop("id", None)
        return out

    # -- IBookRepository ------------------------------------------------
    def list_all(self) -> List[Book]:
        resp = self._table.select("*").order("title").execute()
        return [Book(**row) for row in resp.data or []]

    def get(self, book_id: int) -> Optional[Book]:
        resp = self._table.select("*").eq("id", book_id).limit(1).execute()
        rows = resp.data or []
        return Book(**rows[0]) if rows else None

    def find_by_title(self, title: str) -> Optional[Book]:
        title = self._normalize(title)
        if not title:
            return None
        resp = self._table.select("*").eq("title", title).limit(1).execute()
        rows = resp.data or []
        return Book(**rows[0]) if rows else None

    def find_by_id(self, id: str) -> Optional[Book]:
        id = self._normalize(id)
        if not id:
            return None
        resp = self._table.select("*").eq("id", id).limit(1).execute()
        rows = resp.data or []
        return Book(**rows[0]) if rows else None

    def add(self, book: Book) -> Book:
        row = self._serialize(book.model_dump(), drop_none_id=True)
        resp = self._table.insert(row).execute()
        rows = resp.data or []
        return Book(**rows[0]) if rows else book

    def update(self, book_id: int, **fields) -> Optional[Book]:
        if not fields:
            return self.get(book_id)
        patch = self._serialize(fields)
        resp = self._table.update(patch).eq("id", book_id).execute()
        rows = resp.data or []
        return Book(**rows[0]) if rows else self.get(book_id)

    def delete(self, book_id: int) -> bool:
        resp = self._table.delete().eq("id", book_id).execute()
        return bool(resp.data)

    def title_available(self, title: str) -> bool:
        return self.find_by_title(title) is None